#!/bin/bash

# ---------------------------------------- VARIABLES ----------------------------------------
user=$(whoami);
src_docker="/home/$user/Bureau/Annee_2/SAE/Catalogueur";
nom_fichierSource_html="$1.html";
nom_fichierDest_pdf="$1.pdf";

# ---------------------------------------- DOCKER ----------------------------------------

# --------------- BUILDER ---------------
docker container run --rm -ti -v $src_docker:/work bigpapoo/sae4-php php scripts/builder.php --file $1

# --------------- HTML TO PDF ---------------
docker container run --rm -ti -v $src_docker:/work bigpapoo/sae4-html2pdf "html2pdf sample/$nom_fichierSource_html sample/$nom_fichierDest_pdf"
rm $src_docker/sample/mono.html
